# =============================================================================
# Persistent Volume Claims
# =============================================================================

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlops-outputs-pvc
  namespace: mlops
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: mlops
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage-pvc
  namespace: mlops
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi
